apiVersion: apps/v1
kind: Deployment
metadata:
  name: lotto-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lotto-app
  template:
    metadata:
      labels:
        app: lotto-app
    spec:
      containers:
        - name: lotto-app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DB_NAME
              value: {{ .Values.postgres.db | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
