---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBqI0WTxA8Yqn8fuseRTepOyDDSGD0079O1P0fmA34/zejglz3RzHoCpN4cSlLUNSz/SUf++o98rtzTqkunqOZydM0osxdGtwOP9rA1By3VRFVHnvEzTze7mjxhtJi62rT02Fhv7bQpNx1v6q6OFPRqauDTFTIWOq0LtgiuCM69mXVfhDsNy7Boo/DYu+7fMsW1usv4B2wrHhXL/I9oLn0VHsHOUu+fA6cuVKgMAboP42ZQWmMpOjPx/THelUi6fZYyxeVNTnNfv1wUVHsvXb69mf5lK/DAbVqeyqN9a68KcraXBFob2U6V4lURI6qs8jZV2ea7VoAJoCWOKu318BFIAppEqJ/qHAHfbtOiOvp/Y/wXrtjxUoNdBeQNqFvc6nEn6jsjgfqBClMIB39cBdjMTx5MtPNA/E84VEA9SgRMNsy+VFXY48BiR+WY1QvW4MOXBw1fLbrxdMwCJV7+Sv8ivfpAs2ztd1v6G1GvEsbM1QL6bSkqZvAHq9qhF5meiYTWSAjvh0mpWTbzbWkVbVj/KJCP5cv3PfxCBtSUwJ3u7/NwwYMTdn0X40m6Wg98oN9KOamgJeNK8jyPwEWEiXfpHOqQ/tv895SkeHwjN7q0gW8JG8DDwaYIMqpCwOED0mHFkLpxN7FjM0rhBZA463XO7eWoVIZolxJvyqDuxN+3SE+eM/Vx6JbaVozLu0kmfVFbhw+U4EiX
    username: AgAX81b5cQhJYp50iStMEzRhC2vmZWiUby2xgYZombH1ml6+G++KbeX3LiBDQcKcVw3ZmEHWgcgf3DDovY6d2iQopD3ivFMXJXI+qvuPj3rU+CVqvmCL9CpoSf0Etn4ERBhE/Cpr3Gdm4usGZAAHXp4SauorNk1pc93q2LamBfevIvUZpwg5cNEnPGm4FUpS9yLHKAcz1JkZEQFjIdnhQmpbSuFohqPJrXylKwehmT3PNQHPWa2UjzCANGAh/ZRdwnUoVcgdxZ28gQGFj+SemznR7j0IWyuqCpgT8AvqzpAiSQN9upxzRgn2pkKprUeYspwkFKrPb5KxvYqJvOuzxld//RQVcKyTYhRxpqKzVwXqny+L5YnSP/LHuD7Mea3EEowUnh3IBQBSI/c+1L5NkgGROGCbZ+fSkaa/JYDu0pkKvpxtC+0q1EDkPS4QfDwoL/6TY70VhKFlayfi4eVrocHEoZ6Av+6YvG2wznJ1BlvUGkXOT4gMjW7wIUzjwcI4EYx3p0br3Valn5khoXBi4y6lNR9jGtCKrL61Tb74WL7Y0vwDonnrISZRTTUbqp731HSmbhgzPb+GdUgz2K0H5xnzAHJNfWpDMJd+Un1VD6txelGie+9MzJpHR5Mv0xBbB+07Q9mcORaMvApKZWIEFnPAt99pX4mY74JiBacfgCw7yq6D030TxTkMyA6DPiDytPPMrDtzCP2d
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
