---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgBu1tb2YP6W305/hR3DFPjOFhp4EeB8nAusR1H0Ac1lKIlrgAgRM7V3wny525rafpX/XORTiibeSmaUn3/+q0pKnA4elJbRoTotECO+p+HOSw7w7YCdduVHG1QPzFdYD13xbybN0L+KNFTVluBtezxgkUsXVWiXiSwT6oIHBq/suxWBkwYzWoH5sjpQjXX0ekzBjXIOQEbwkNd9k6zLX6a7DNMdpZtyBYBpdTjWMrIEMnHwOCjFTdCfo3M7r0WL6KNh9tg+9NU4/QRoGGaHluo8NFnzFXES3vZylVfSU3DPWRytc2UTFAAF78CRm8e0fRcmhxfyEvqnq3M4YwAXqrEynaDLjxzr2g4jrETRg3kx1XkJz/Ed7lOGS7kVY8nWr2kRMIkTsquLtY5eLM7mBqhQPyr7RIr09lKhCUy11jQ3tj9nnDWL9PYTql8HMvy4SAiBeVHHNoq1sXcip3wH1y4TDMAR8oHC36MOPXhx5FSAr46u6iQSVdn7O9w/SzHrLI7NrjXiz207TNeaRn6UTfVoTgL2unC3esim0LWzO2MwSJtr3HDMqnSyndMhIuWzNcEteTVf2zKnFkKty/DlT3mIlo90iAUNf/B4D4bz0KpAO6IyPcQrXcj24+bpc2VtRku2qkbCU+lLWb/wMH+ncaHK18IArRp2lZDoTEHW+0cTY8i/gc0QaYN3/ITlR5yDBo/XW6rls3nJ
    username: AgBcmCoBogKPzQXTqksMmrCPT8PjpvEk6zeqw7l/2KaeV5Qyy99dw7E59qKfEZoF2BjSLv47/ou4piyzs8qbq8zPbHmg4q0ylaH4ui6lJeo5vQTt0EKZCpptEqxn0t4Jp6ZHZl8UXEw9BjLnV/fHJKCpiQknLA/KM1IxB6CGzbdEgPT23j7r6l5VnZPjo0+AfkcTn1i24xZbsb8gKn+xyxHiYOIisTCJHPzngNnK2dZwhMnm88a6RV7tvfO+xAf8vIBervxiModPc2mwr8GpaEyorrjxB6SJ1HbWi5rDS8VZjA4PHW5NRtAO0WzHOBmJ+LzjS5YY3EeU/odh2U11YjzXbvLVv/4z+V3PGl1w3ZKe54lzHMI3SZSKo72vzM7ctMhT6+cBlt6z/2VwQ5TGAKXhHf+WNPsQV58WYJ1bb6mvFxOeOzPiWv0nOiX+rQFoP98NXlS3pgVx7CPijX2kho/sK+aGZ/xzRBrNwpW4yz5gwSgi1YiKgvfzfmeWRCBDtUZl1538RLEBJdlcB83j24axVcPl+Hobf/2MWVZapyWhnd0/YtDD3DRvHO94g0/KY0SKExemrA55j/nWwrgmJzbYUYCK+WYl8BsYGZNwY23/voTe9DHm2w4BtEutnwfNqOu1hn/hy58hSPqTVZNeW0OOAjmDB4BKiF301aarzgj1RDd7k4sl2BCOdFTx7TJJygltlAbw6884
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
