---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-secret
  namespace: default
spec:
  encryptedData:
    password: AgCKAm4vjQ2aqYKfBa5S1+k/LnoLaKLoz9Cm3+UEPxStfTHuW2/zlAYlQ25qz2CZhAcD4zrDUzW3aVR/rTmyWcBhqo7i6JEcsewpKcMbCTTlB3psWnkfjicDmKrsd8vy78w80m8eRYUFaU8POj/L7eqjpD3rwSLRBd4+I/WZkciqjsf0tuPffqXGaWScVnIj363B9shBlyWhUUapxJnQRUv3te4YO5lF4MwakcXPLjVS0ovnoU37G6UBGLRNlDZXdJIhP/VtEhzwNo9fr96zxePzOD9SzO6+L/Xska1GJ37XRvxRnK6fp4ZdGQ4tmw+yULEBpacLM/E1XNlNJoC7hAQ8en2K7IpSLZk/37qsesDQ4uvLcVwVpYe6MDQ/agHfCKcbd9GShxB6JbpsyZ94g1dhbDOO96FZ/b7lkkgk4wMA1Q48ixeeLYF4hHLlhMRYHGdckP/AA3gUzmsaJMUPjBeYgDlKOnX+Knn/hgC1uH3VJhROvsy+xBz+DBP+ApaPnEaEu5M4k72A3wjNhkfDbKHltjt+lTGBeWCN8nutULq9bX2uoS8E0D1yuC2qzwNeTHcwTFMzrhhYLw2SSWk1cznChyrb9+TWizrlKq4/m0zf8AnfWXTejw3hl7MxhWH+T2RMcPzcfMZ3x76HHupU0bn7V8MtzFFfqBX9OHwGGJnXyYS2gmbuJLjyuo2qmxNJ8x+JL/OHaqtQ
    username: AgBBkFI78bAujZI1jExsyOBh766rOp0w6UFSwjOKf51uN8YxqH1Z0ZUbBykD0X6/wgpGlBNpRJc1ylRrevTE2kHMIkIJ5VfBD/VENsPIKy/TSnOSHtJ1AQjgouxWNYP/18e8KklCerqG6obtQvbLNfc4WEcImRFpQ33hTW00pLXZIu4NZugLTMyHytq2WW/+OqwUxkKVz3QD62avh9z56Fr0e++6smlnk+h2EQbgzG6STJbeJjv2WXXM1kl91ISDbnQn+k2a7CUkf4HfS7tenrOIdvBSZ20c2lW62yLSR8DJOwsTGkMbqsw3XBl8BK7i9fF2KxJDuzNmumjbcwhw+XHPG4Y7xcQI4D2ndwHidvgZjMntQWDUb5JwhA6aYYScq+1wlmn/Kk93Gtm/hmN05dOMReyNfhphgB9xekp3Nezi38rTk1h91msPrIDdDUwAsjUR5bqqpfZA7LHPtIKOx1DAfBVv0s+E+6u/oOTAoRv3634nOBrw0FpDZLGRoK3ZQmNJdlBT1V9hrZ36MI20sgzbw9YY+ZdGM4cMFs+pLkiKEhA3oQ23DdDsKjQA89W65+KLlPcLhOVnIPM0PnHbYLsrAisG96gMz7/9cDgraptjyeylsYrdT1/dhZ9RB3DYFwVZwLuLIXMMD76YtBgXDKDKnfNahsG1bf8kNUcj4VqIw33FuPpIaHjBj1UwOpIPchwTsujKTLh5
  template:
    metadata:
      creationTimestamp: null
      name: db-secret
      namespace: default
    type: Opaque
